@request = http://localhost:5500
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTIxYjQ0N2Y1OGIzZTI5ODIyZmViNWUiLCJpYXQiOjE2Mjk1OTg3OTl9.L4b1Wu4KNlinLaRElOsbir7DPzGHMCXSyucMbwdIhaM

### Test
GET {{request}}

### Register user
POST {{request}}/user/register
Content-Type: application/json

{
    "email": "user1@planner.com",
    "password": "123456",
    "firstname": "user",
    "lastname": "planner",
    "address": "Schaden Junction",
    "gender": "male"
}

### Login
POST {{request}}/user/login
Content-Type: application/json

{
    "email": "user1@planner.com",
    "password": "123456"
}


### User Profile
GET {{request}}/user
Authorization: {{token}}

### Add Todo
POST {{request}}/todo
Content-Type: application/json
Authorization: {{token}}

{
    "title":"Complete Assignment", 
    "description": "Complete planner android application with api", 
    "schedule": "2023/02/25", 
    "priority": "high"
}

### Get todos
GET {{request}}/todo
Authorization: {{token}}

### Toggle complete
PUT {{request}}/todo/toggle/6121b479f58b3e29822feb64
Authorization: {{token}}

### Edit Todo
PUT {{request}}/todo/edit/6121b479f58b3e29822feb64
Content-Type: application/json
Authorization: {{token}}

{
    "title":"Complete Android", 
    "description": "Complete planner android application", 
    "schedule": "2023/01/25", 
    "priority": "low"
}