@request = http://localhost:5500
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTIwOTdjYTY3YjgwMDQyYzdkZjc1Y2MiLCJpYXQiOjE2Mjk1MzY4MjZ9.U7Fi2HuvhqarxAVhB6pTqXhZiZuR_CU2NJvnDJQp_tQ

### Test
GET {{request}}

### Register user
POST {{request}}/user/register
Content-Type: application/json

{
    "email": "user1@planner.com",
    "password": "123456",
    "firstname": "user",
    "lastname": "planner",
    "address": "Schaden Junction",
    "gender": "male"
}

### Login
GET {{request}}/user/login
Content-Type: application/json

{
    "email": "user1@planner.com",
    "password": "123456"
}


### User Profile
GET {{request}}/user
Authorization: Bearer {{token}}