@request = http://localhost:5500
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTIxM2ZlOWNmOWM5NjZjMTUzZDU1MmYiLCJpYXQiOjE2Mjk1NjkwMDR9.FxmEA4YW7IngHmjcc0rrXH4MEJS7IB4PfYG-AVg5dOs

### Test
GET {{request}}

### Register user
POST {{request}}/user/register
Content-Type: application/json

{
    "email": "user1@planner.com",
    "password": "123456",
    "firstname": "user",
    "lastname": "planner",
    "address": "Schaden Junction",
    "gender": "male"
}

### Login
GET {{request}}/user/login
Content-Type: application/json

{
    "email": "user1@planner.com",
    "password": "123456"
}


### User Profile
GET {{request}}/user
Authorization: Bearer {{token}}

### Add Todo
POST {{request}}/todo
Authorization: Bearer {{token}}

{
    "title":"Complete API", 
    "description": "Complete planner api", 
    "schedule": "2023/01/22", 
    "priority": "high"
}

### Get Plans
GET {{request}}/todo
Authorization: Bearer {{token}}